#!/usr/bin/env python3

# Generate a C array from a font file.

with open("roboto.ttf", "rb") as f:
    data = f.read()
    print("/* Generated by gen-font-stream.py, DO NOT EDIT! */\n")
    print("unsigned char roboto_ttf[] = {")
    for i, b in enumerate(data):
        print(f"0x{b:02x},", end=" " if (i+1)%12 else "\n")
    print("};")
    print(f"unsigned int roboto_ttf_len = {len(data)};")